In [17]:
import pandas as pd

# GitLinkXLS='https://raw.githubusercontent.com/reconjohn/evans/master/solar.csv'
# SolarCapa=pd.read_csv(GitLinkXLS)[pd.read_csv(GitLinkXLS).Year==2017]
# SolarCapa.drop(columns='Year',inplace=True)
# SolarCapa.columns=['Country','SolarCapacityGW']

In [78]:
GitLinkXLS='https://docs.google.com/spreadsheets/d/e/2PACX-1vQQ_ePBaN0RuAw0aHdA4tNwScjDe6v6m2O342Hv9bekJyJADPmj_1Qg0VJwapzC4bZosu15CRhePpca/pub?gid=0&single=true&output=csv'

Education=pd.read_csv(GitLinkXLS).drop(columns=['EIRank','ExpectedYears','MeanYears','HDI','Continent'])
Education

          Country  EducationIndex
0       Australia           0.939
1         Denmark           0.923
2     New Zealand           0.917
3          Norway           0.916
4         Germany           0.914
..            ...             ...
183   South Sudan           0.297
184          Chad           0.280
185       Eritrea           0.267
186  Burkina Faso           0.262
187         Niger           0.206

[188 rows x 2 columns]

In [144]:
Education.Country.tolist()

['Australia',
 'Denmark',
 'New Zealand',
 'Norway',
 'Germany',
 'Ireland',
 'Iceland',
 'United States',
 'Netherlands',
 'United Kingdom',
 'Switzerland',
 'Canada',
 'Slovenia',
 'Lithuania',
 'Czech Republic',
 'Estonia',
 'Israel',
 'South Korea',
 'Sweden',
 'Poland',
 'Finland',
 'Japan',
 'Belgium',
 'France',
 'Latvia',
 'Belarus',
 'Hungary',
 'Greece',
 'Slovakia',
 'Hong Kong',
 'Austria',
 'Liechtenstein',
 'Spain',
 'Russian Federation',
 'Italy',
 'Singapore',
 'Argentina',
 'Palau',
 'Kazakhstan',
 'Ukraine',
 'Croatia',
 'Montenegro',
 'Georgia',
 'Cyprus',
 'Chile',
 'Luxembourg',
 'Malta',
 'Cuba',
 'Bulgaria',
 'Fiji',
 'Romania',
 'Barbados',
 'Saudi Arabia',
 'Tonga',
 'Serbia',
 'Portugal',
 'Sri Lanka',
 'Uzbekistan',
 'Mongolia',
 'Armenia',
 'Grenada',
 'Mauritius',
 'Moldova',
 'Azerbaijan',
 'Kyrgyzstan',
 'Andorra',
 'Bahrain',
 'Trinidad and Tobago',
 'Uruguay',
 'Brunei Darussalam',
 'Albania',
 'Bahamas',
 'Venezuela',
 'Seychelles',
 'South Africa',
 'Belize',
 'Iran',
 'Samoa',
 'Jordan',
 'Malaysia',
 'Qatar',
 'Antigua and Barbuda',
 'Bosnia and Herzegovina',
 'Panama',
 'United Arab Emirates',
 'Costa Rica',
 'Brazil',
 'Jamaica',
 'Saint Lucia',
 'Macedonia',
 'Peru',
 'Turkey',
 'Ecuador',
 'Saint Kitts and Nevis',
 'Algeria',
 'Botswana',
 'Tajikistan',
 'Saint Vincent and the Grenadines',
 'Bolivia',
 'Lebanon',
 'Mexico',
 'Palestine',
 'Oman',
 'Micronesia',
 'Tunisia',
 'Thailand',
 'Philippines',
 'China',
 'Colombia',
 'Suriname',
 'Turkmenistan',
 'India',
 'Dominican Republic',
 'Indonesia',
 'Dominica',
 'Gabon',
 'Viet Nam',
 'Libya',
 'Paraguay',
 'Kuwait',
 'Egypt',
 'Kiribati',
 'El Salvador',
 'Zambia',
 'Guyana',
 'Maldives',
 'Ghana',
 'Pakistan',
 'Namibia',
 'Swaziland',
 'Zimbabwe',
 'Nicaragua',
 'Cabo Verde',
 'Vanuatu',
 'Congo',
 'Honduras',
 'Kenya',
 'Sao Tome and Principe',
 'Guatemala',
 'Lesotho',
 'Morocco',
 'Iraq',
 'Timor-Leste',
 'Cameroon',
 'Madagascar',
 'Togo',
 'Angola',
 'Nigeria',
 'Democratic Republic of the Congo',
 'Nepal',
 'Laos',
 'Comoros',
 'Uganda',
 'Cambodia',
 'Bangladesh',
 'Bhutan',
 'Malawi',
 'Solomon Islands',
 'Tanzania',
 'Equatorial Guinea',
 'Rwanda',
 'Haiti',
 'Liberia',
 'Papua New Guinea',
 'Syrian Arab Republic',
 "Cote d'Ivoire",
 'Benin',
 'Myanmar',
 'Afghanistan',
 'Burundi',
 'Mauritania',
 'Sierra Leone',
 'Mozambique',
 'Gambia',
 'Senegal',
 'Guinea-Bissau',
 'Yemen',
 'Central African Republic',
 'Guinea',
 'Ethiopia',
 'Sudan',
 'Mali',
 'Djibouti',
 'South Sudan',
 'Chad',
 'Eritrea',
 'Burkina Faso',
 'Niger']

In [130]:
from urllib.request import urlopen

GitLinkXLS='https://github.com/tygris/PUBPOL_GovAnalytics/raw/master/tax.pkl'
Tax=pd.read_pickle(urlopen(GitLinkXLS),compression=None)

country_fix = {'Czechia': 'Czech Republic',
               'Korea, South': 'South Korea',
               'Russia': 'Russian Federation',
               'Brunei': 'Brunei Darussalam',
               'Bahamas, The': 'Bahamas',
               'West Bank': 'Palestine',
               'Micronesia, Federated States of': 'Micronesia',
               'Vietnam': 'Viet Nam',
               'Eswatini': 'Swaziland',
               'Congo, Republic of the': 'Congo',
               'Congo, Democratic Republic of the': 'Democratic Republic of the Congo',
               'Syria': 'Syrian Arab Republic',
               'Burma': 'Myanmar',
               'Gambia, The': 'Gambia'}

# use the dictionary
Tax.Country.replace(country_fix,inplace=True)

Tax.head()

     Country  taxRevenuePercentGDP
0     Tuvalu                 1.067
1      Nauru                 0.903
2  Greenland                 0.774
3   Kiribati                 0.768
4    Andorra                 0.690

In [131]:
Tax.Country.tolist()

['Tuvalu',
 'Nauru',
 'Greenland',
 'Kiribati',
 'Andorra',
 'Palau',
 'Micronesia',
 'Cuba',
 'Norway',
 'France',
 'Finland',
 'Denmark',
 'Marshall Islands',
 'Libya',
 'Belgium',
 'Sweden',
 'Greece',
 'Austria',
 'Anguilla',
 'Italy',
 'Croatia',
 'Germany',
 'Hungary',
 'Luxembourg',
 'Venezuela',
 'Bosnia and Herzegovina',
 'Netherlands',
 'Slovenia',
 'Portugal',
 'Serbia',
 'Iceland',
 'Kuwait',
 'Solomon Islands',
 'Dominica',
 'Belarus',
 'San Marino',
 'Czech Republic',
 'Malta',
 'Bolivia',
 'Cyprus',
 'Estonia',
 'Tonga',
 'Lesotho',
 'Seychelles',
 'Poland',
 'French Polynesia',
 'Slovakia',
 'Canada',
 'United Kingdom',
 'British Virgin Islands',
 'Cayman Islands',
 'Spain',
 'American Samoa',
 'Latvia',
 'Montenegro',
 'New Zealand',
 'Brazil',
 'Bulgaria',
 'Iraq',
 'Switzerland',
 'Australia',
 'Djibouti',
 'Japan',
 'Eritrea',
 'Lithuania',
 'Falkland Islands (Islas Malvinas)',
 'Algeria',
 'Namibia',
 'Ecuador',
 'Saint Kitts and Nevis',
 'Tajikistan',
 'Northern Mariana Islands',
 'Oman',
 'Uzbekistan',
 'Botswana',
 'Faroe Islands',
 'Moldova',
 'Belize',
 'Uruguay',
 'Fiji',
 'Jamaica',
 'Barbados',
 'Angola',
 'Romania',
 'Macau',
 'Cook Islands',
 'Kosovo',
 'Macedonia',
 'Virgin Islands',
 'United Arab Emirates',
 'Georgia',
 'Kyrgyzstan',
 'Saint Vincent and the Grenadines',
 'Swaziland',
 'Samoa',
 'Guyana',
 'Nicaragua',
 'Cabo Verde',
 'Albania',
 'Mauritania',
 'Bhutan',
 'Vanuatu',
 'Peru',
 'Saint Pierre and Miquelon',
 'Mozambique',
 'Mongolia',
 'South Africa',
 'Ukraine',
 'Colombia',
 'Israel',
 'Maldives',
 'Qatar',
 'Saudi Arabia',
 'Sao Tome and Principe',
 'Ireland',
 'Grenada',
 'Comoros',
 'Aruba',
 'Viet Nam',
 'Tunisia',
 'Trinidad and Tobago',
 'Nepal',
 'El Salvador',
 'Jordan',
 'Saint Lucia',
 'Azerbaijan',
 'Gibraltar',
 'Hong Kong',
 'South Korea',
 'Armenia',
 'Mexico',
 'Congo',
 'Mauritius',
 'Kazakhstan',
 'Malawi',
 'Lebanon',
 'Togo',
 'Zimbabwe',
 'Guam',
 'Niger',
 'China',
 'Rwanda',
 'Burkina Faso',
 'Morocco',
 'Chile',
 'Guernsey',
 'New Caledonia',
 'Gambia',
 'Ghana',
 'Honduras',
 'Turkey',
 'Panama',
 'Mali',
 'Antigua and Barbuda',
 'Senegal',
 "Cote d'Ivoire",
 'Argentina',
 'Brunei Darussalam',
 'Sudan',
 'Papua New Guinea',
 'Laos',
 'Guinea-Bissau',
 'Haiti',
 'Cambodia',
 'Egypt',
 'Bahamas',
 'Gabon',
 'Kenya',
 'Zambia',
 'Iran',
 'Benin',
 'United States',
 'Equatorial Guinea',
 'Liberia',
 'Wallis and Futuna',
 'Bahrain',
 'Curacao',
 'Guinea',
 'Jersey',
 'Malaysia',
 'Russian Federation',
 'Suriname',
 'Bermuda',
 'Taiwan',
 'Madagascar',
 'Burundi',
 'Singapore',
 'Philippines',
 'Sierra Leone',
 'Pakistan',
 'Cameroon',
 'Tanzania',
 'Thailand',
 'Dominican Republic',
 'Liechtenstein',
 'Monaco',
 'Turkmenistan',
 'Central African Republic',
 'Uganda',
 'Costa Rica',
 'Isle of Man',
 'Paraguay',
 'Ethiopia',
 'Sri Lanka',
 'Myanmar',
 'Chad',
 'Palestine',
 'Indonesia',
 'Korea, North',
 'Afghanistan',
 'Democratic Republic of the Congo',
 'Guatemala',
 'Timor-Leste',
 'Bangladesh',
 'India',
 'Yemen',
 'Puerto Rico',
 'South Sudan',
 'Syrian Arab Republic',
 'Nigeria',
 'Somalia']

In [147]:
GitLinkXLS='https://raw.githubusercontent.com/abunnell-source/GroupData/master/DFnew.csv'
Religion=pd.read_csv(GitLinkXLS).loc[:,['Country','ReligionImportant']]

# dictionary to change 'Country' names
country_fix2 = {'Vietnam': 'Viet Nam',
 'The Netherlands': 'Netherlands',
 'Russia': 'Russian Federation',
 'North Macedonia': 'Macedonia',
 'Syria': 'Syrian Arab Republic',
 'State of Palestine': 'Palestine',
 'Republic of the Congo': 'Congo'}
# use the dictionary

Religion.Country.replace(country_fix2,inplace=True)

Religion.head()

          Country  ReligionImportant
0         Estonia               0.16
1          Sweden               0.17
2         Denmark               0.19
3          Norway               0.21
4  Czech Republic               0.21

In [148]:
Religion.Country.tolist()

['Estonia',
 'Sweden',
 'Denmark',
 'Norway',
 'Czech Republic',
 'Japan',
 'Hong Kong',
 'United Kingdom',
 'Finland',
 'Viet Nam',
 'France',
 'Australia',
 'Netherlands',
 'New Zealand',
 'Belgium',
 'Cuba',
 'Bulgaria',
 'Russian Federation',
 'Belarus',
 'Luxembourg',
 'Hungary',
 'Albania',
 'Latvia',
 'Germany',
 'Uruguay',
 'Switzerland',
 'Canada',
 'Lithuania',
 'South Korea',
 'Kazakhstan',
 'Taiwan',
 'Ukraine',
 'Slovenia',
 'Slovakia',
 'Spain',
 'Azerbaijan',
 'Israel',
 'Serbia',
 'Ireland',
 'Austria',
 'Uzbekistan',
 'Belize',
 'Argentina',
 'United States',
 'Croatia',
 'Chile',
 'Singapore',
 'Jamaica',
 'Montenegro',
 'Greece',
 'Portugal',
 'Italy',
 'Moldova',
 'Kyrgyzstan',
 'Iran',
 'Mexico',
 'Armenia',
 'Poland',
 'Haiti',
 'Cyprus',
 'Macedonia',
 'Botswana',
 'Bosnia and Herzegovina',
 'Venezuela',
 'Costa Rica',
 'Turkmenistan',
 'Togo',
 'Georgia',
 'Turkey',
 'Ecuador',
 'Colombia',
 'El Salvador',
 'Peru',
 'Iraq',
 'Nicaragua',
 'Honduras',
 'Romania',
 'South Africa',
 'Puerto Rico',
 'Tajikistan',
 'Mozambique',
 'Malta',
 'Brazil',
 'Dominican Republic',
 'Lebanon',
 'Zimbabwe',
 "Cote d'Ivoire",
 'Burkina Faso',
 'Panama',
 'Angola',
 'Guatemala',
 'Tanzania',
 'Bolivia',
 'Syrian Arab Republic',
 'India',
 'United Arab Emirates',
 'Kuwait',
 'Namibia',
 'Trinidad and Tobago',
 'Paraguay',
 'Pakistan',
 'Palestine',
 'Sudan',
 'Uganda',
 'Madagascar',
 'Benin',
 'Nepal',
 'Tunisia',
 'Saudi Arabia',
 'Central African Republic',
 'Kenya',
 'Liberia',
 'Democratic Republic of the Congo',
 'Bahrain',
 'Ghana',
 'Zambia',
 'Qatar',
 'Algeria',
 'Chad',
 'Rwanda',
 'Congo',
 'Mali',
 'Philippines',
 'Cameroon',
 'Malaysia',
 'Nigeria',
 'Cambodia',
 'Senegal',
 'Jordan',
 'Myanmar',
 'Afghanistan',
 'Laos',
 'Guinea',
 'Morocco',
 'Egypt',
 'Comoros',
 'Thailand',
 'Burundi',
 'Djibouti',
 'Mauritania',
 'Sri Lanka',
 'Malawi',
 'Indonesia',
 'Yemen',
 'Niger',
 'Ethiopia',
 'Somalia',
 'Bangladesh',
 'Oman']

In [149]:
len(Education), len(Tax), len(Religion)

(188, 221, 149)

In [150]:
Data=Education.merge(Tax,how='inner').merge(Religion,how='inner')

In [152]:
Data.columns

Index(['Country', 'EducationIndex', 'taxRevenuePercentGDP',
       'ReligionImportant'],
      dtype='object')

In [153]:
Data=Data.dropna()
Data.reset_index(drop=True,inplace=True)
Data.head()

       Country  EducationIndex  taxRevenuePercentGDP  ReligionImportant
0    Australia           0.939                 0.355               0.32
1      Denmark           0.923                 0.530               0.19
2  New Zealand           0.917                 0.368               0.33
3       Norway           0.916                 0.544               0.21
4      Germany           0.914                 0.450               0.40

In [154]:
Data

          Country  EducationIndex  taxRevenuePercentGDP  ReligionImportant
0       Australia           0.939                 0.355               0.32
1         Denmark           0.923                 0.530               0.19
2     New Zealand           0.917                 0.368               0.33
3          Norway           0.916                 0.544               0.21
4         Germany           0.914                 0.450               0.40
..            ...             ...                   ...                ...
141          Mali           0.312                 0.200               0.95
142      Djibouti           0.310                 0.353               0.98
143          Chad           0.280                 0.135               0.95
144  Burkina Faso           0.262                 0.212               0.88
145         Niger           0.206                 0.214               1.00

[146 rows x 4 columns]

In [155]:
Data.Country.tolist()

['Australia',
 'Denmark',
 'New Zealand',
 'Norway',
 'Germany',
 'Ireland',
 'United States',
 'Netherlands',
 'United Kingdom',
 'Switzerland',
 'Canada',
 'Slovenia',
 'Lithuania',
 'Czech Republic',
 'Estonia',
 'Israel',
 'South Korea',
 'Sweden',
 'Poland',
 'Finland',
 'Japan',
 'Belgium',
 'France',
 'Latvia',
 'Belarus',
 'Hungary',
 'Greece',
 'Slovakia',
 'Hong Kong',
 'Austria',
 'Spain',
 'Russian Federation',
 'Italy',
 'Singapore',
 'Argentina',
 'Kazakhstan',
 'Ukraine',
 'Croatia',
 'Montenegro',
 'Georgia',
 'Cyprus',
 'Chile',
 'Luxembourg',
 'Malta',
 'Cuba',
 'Bulgaria',
 'Romania',
 'Saudi Arabia',
 'Serbia',
 'Portugal',
 'Sri Lanka',
 'Uzbekistan',
 'Armenia',
 'Moldova',
 'Azerbaijan',
 'Kyrgyzstan',
 'Bahrain',
 'Trinidad and Tobago',
 'Uruguay',
 'Albania',
 'Venezuela',
 'South Africa',
 'Belize',
 'Iran',
 'Jordan',
 'Malaysia',
 'Qatar',
 'Bosnia and Herzegovina',
 'Panama',
 'United Arab Emirates',
 'Costa Rica',
 'Brazil',
 'Jamaica',
 'Macedonia',
 'Peru',
 'Turkey',
 'Ecuador',
 'Algeria',
 'Botswana',
 'Tajikistan',
 'Bolivia',
 'Lebanon',
 'Mexico',
 'Palestine',
 'Oman',
 'Tunisia',
 'Thailand',
 'Philippines',
 'Colombia',
 'Turkmenistan',
 'India',
 'Dominican Republic',
 'Indonesia',
 'Viet Nam',
 'Paraguay',
 'Kuwait',
 'Egypt',
 'El Salvador',
 'Zambia',
 'Ghana',
 'Pakistan',
 'Namibia',
 'Zimbabwe',
 'Nicaragua',
 'Congo',
 'Honduras',
 'Kenya',
 'Guatemala',
 'Morocco',
 'Iraq',
 'Cameroon',
 'Madagascar',
 'Togo',
 'Angola',
 'Nigeria',
 'Democratic Republic of the Congo',
 'Nepal',
 'Laos',
 'Comoros',
 'Uganda',
 'Cambodia',
 'Bangladesh',
 'Malawi',
 'Tanzania',
 'Rwanda',
 'Haiti',
 'Liberia',
 'Syrian Arab Republic',
 "Cote d'Ivoire",
 'Benin',
 'Myanmar',
 'Afghanistan',
 'Burundi',
 'Mauritania',
 'Mozambique',
 'Senegal',
 'Yemen',
 'Central African Republic',
 'Guinea',
 'Ethiopia',
 'Sudan',
 'Mali',
 'Djibouti',
 'Chad',
 'Burkina Faso',
 'Niger']

In [123]:
Data.to_csv('Data.csv', index=False)